on:
  release:
    types: [published]
name: Build Release
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup go environment
        uses: actions/setup-go@v2
      - name: Install system dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
      - name: Install go dependencies
        run: go mod download
      - name: Build release
        run: go build -tags static -ldflags "-s -w" -o microworlds.bin
        env:
          GOARCH: amd64
          GOOS: linux
          CGO_ENABLED: 1
          CC: gcc
      - name: Compress artifacts
        run: tar zcvf microworlds-${{ github.event.release.tag_name }}.tar.gz microworlds.bin
      - name: Upload the artifacts to release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: microworlds-${{ github.event.release.tag_name }}.tar.gz
          tag: ${{ github.ref }}
  release-windows:
    name: release windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup msys
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-go mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_gfx zip
      - name: Build release
        run: go build -tags static -ldflags "-s -w" -o microworlds.exe
        env:
          GOARCH: amd64
          GOOS: windows
          CGO_ENABLED: 1
          CC: gcc
      - name: Compress artifacts
        run: zip microworlds-${{ github.event.release.tag_name }}.zip microworlds.exe
      - name: Upload the artifacts to release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: microworlds-${{ github.event.release.tag_name }}.zip
          tag: ${{ github.ref }}

