on:
  release:
    types: [published]
name: Build Release
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup go environment
        uses: actions/setup-go@v2
      - name: Install system dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
      - name: Install go dependencies
        run: go mod download
      - name: Build release
        run: go build -o microworlds.bin
        env:
          GOARCH: amd64
          GOOS: linux
      - name: Compress artifacts
        run: tar zcvf microworlds-${{ github.event.release.tag_name }}.tar.gz microworlds.bin
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: microworlds-${{ github.event.release.tag_name }}.tar.gz